language: ruby
rvm:
  - "2.4.1"
env:
  - DB=postgresql
script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:seed RAILS_ENV=test
  - bundle exec rspec
